name: "Github Issue PreCheck"

description: "Check new opened issue."

author: "Replicated Collab"

branding:
  icon: "terminal"
  color: "white"

inputs:
  github-token:
    description: GITHUB_TOKEN token or a PAT
    required: true

runs:
  using: "node16"
  main: "index.js"
