name: "Slash Commands"

description: "Check comments for /commands"

author: "Replicated Collab"

branding:
  icon: "terminal"
  color: "white"

inputs:
  github-token:
    description: GITHUB_TOKEN token or a PAT
    required: true

  command:
    description: The command to act on
    required: true

  allowVendor:
    description: Does Vendor allow to run the command
    required: true

outputs:
  command-name:
    description: The name of the command

  command-arguments:
    description: The arguments of the command

runs:
  using: "node16"
  main: "index.js"
