name: Check New Issues

on:
  issues:
    types: [opened]

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Copy Github Issue PreCheck
      run: cp -r .github/workflows/github-issue-pre-check ./
    - name: Check new issue
      uses: ./github-issue-pre-check
      id: precheck
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
